[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "henocy"
version = "1.0.0"
authors = [
    { name="Ace Create", email="salomjaga@gmail.com" },
]
description = "Professional EXIF viewer, image resizer, converter and hashing tool suite."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "Pillow>=9.0.0",
    "requests>=2.28.0"
]

[tool.setuptools.packages.find]
where = ["."]
